// SPDX-License-Identifier: GPL-3.0-or-later
// Independent synthetic tests; no private source identifiers or bytes.
#include "verified_idioms.h"
#include "ir/dolir_builder.h"
#include <iostream>
#include <functional>
#include <map>
#include <random>
#include <stdexcept>
#include <cstring>
using namespace dolidiom;
#ifdef REVIEW_WRAP_VERIFIER
static bool refuse_next_verification=false;
extern "C" bool __real_dolir_verify(const DolIRModule*,FILE*);
extern "C" bool __wrap_dolir_verify(const DolIRModule*m,FILE*f){if(refuse_next_verification){refuse_next_verification=false;return false;}return __real_dolir_verify(m,f);}
#endif
static void require(bool x,const char*s){if(!x)throw std::runtime_error(s);}
struct M {DolIRModule m{};DolIRValue root=0;M(){dolir_module_init(&m);}~M(){dolir_module_free(&m);}DolIRFunction&f(){return m.functions[0];}};
static DolIRValue binary(DolIRFunction&f,DolIRBlock&b,DolIROp op,DolIRValue x,DolIRValue y){DolIRValue a[]={x,y};return dolir_append(&f,&b,op,DOLIR_TYPE_I32,a,2,0,0,b.guest_address,0);}
static void local(M&m,bool wrong=false){auto*f=dolir_add_function(&m.m,"synthetic_arithmetic",0x1000,0x1004);auto*b=dolir_add_block(f,0x1000);b->raw=0x60000000;b->cycle_cost=1;auto x=dolir_state_read(f,b,DolIRStateSlot(DOLIR_STATE_GPR0+7),0x1000);auto c=[&](u32 n){return dolir_constant(f,b,DOLIR_TYPE_I32,n,0x1000);};auto sign=binary(*f,*b,wrong?DOLIR_OP_LSHR:DOLIR_OP_ASHR,x,c(31));auto bias=binary(*f,*b,DOLIR_OP_AND,sign,c(31));auto sum=binary(*f,*b,DOLIR_OP_ADD,x,bias);auto rounded=binary(*f,*b,DOLIR_OP_AND,sum,c(~31u));m.root=binary(*f,*b,DOLIR_OP_SUB,x,rounded);dolir_state_write(f,b,DOLIR_STATE_GPR31,sign,0x1000);auto lr=dolir_state_read(f,b,DOLIR_STATE_LR,0x1000);b->terminator.kind=DOLIR_TERM_INDIRECT;b->terminator.target_value=binary(*f,*b,DOLIR_OP_AND,lr,c(~3u));b->terminator.condition=dolir_constant(f,b,DOLIR_TYPE_I1,1,0x1000);b->terminator.guest_pc=0x1000;require(dolir_verify(&m.m,stderr),"local synthetic invalid");}
static void realBuilder(M&m,bool barrier=false){std::vector<u32>w={(31u<<26)|(3<<21)|(4<<16)|(31<<11)|(824<<1),(21u<<26)|(4<<21)|(4<<16)|(29<<6)|(31<<1),(31u<<26)|(5<<21)|(3<<16)|(4<<11)|(266<<1),(21u<<26)|(5<<21)|(5<<16)|(29<<6)|(31<<1),(31u<<26)|(3<<21)|(4<<16)|(5<<11)|(40<<1),0x4e800020};if(barrier)w.insert(w.begin()+2,0x812a0000);std::vector<PPCInst>p;for(auto v:w)p.push_back(ppc_decode(v,0x2000+4*p.size()));require(dolir_build_chunk(&m.m,p.data(),p.size(),0x2000)&&dolir_verify(&m.m,stderr),"actual synthetic builder invalid");}
static dolcert::Contract verifiedEnvironment(const DolIRFunction&f){dolcert::Contract c;c.source_fingerprint=sourceFingerprint(f);c.entries_and_code=c.observations=c.exception_resume={dolcert::EvidenceGrade::Verified,"independent-controlled-synthetic-environment-v1"};auto fp=c.source_fingerprint;c.verify_evidence=[fp](const dolcert::EvidenceRequest&r){return r.source_fingerprint==fp&&r.entry_blocks==std::vector<u32>{0}&&r.model=="exact-original-cuts/full-state-observation"&&r.proof_id=="independent-controlled-synthetic-environment-v1"&&(r.obligation=="ENTRY_POPULATION_OR_CODE_STABILITY_UNPROVED"||r.obligation=="EXCEPTION_RESUME_CLOSURE_UNPROVED"||r.obligation=="EXACT_OBSERVATION_AND_MUTATION_CONTRACT_UNPROVED");};return c;}
static RegionContract allowed(const DolIRFunction&f,const Candidate&c){RegionContract r;r.function=verifiedEnvironment(f);r.source_cut_fingerprint=sourceCutFingerprint(f);r.roots={c.root};return r;}
static Candidate find(const Report&r,unsigned k,DolIRValue root=0){for(auto&c:r.candidates)if(c.expression.power==k&&c.proof.status=="UNSAT"&&(!root||root==c.root))return c;throw std::runtime_error("expected automatically discovered UNSAT candidate missing");}
static std::map<u32,u32> evaluate(const DolIRFunction&f,u32 input){std::map<u32,u32>v;for(u32 b=0;b<f.block_count;++b)for(u32 j=0;j<f.blocks[b].instruction_count;++j){const auto&i=f.blocks[b].instructions[j];if(!i.result)continue;u32 a=v[i.operands[0]],c=v[i.operands[1]],out=0;switch(i.op){case DOLIR_OP_CONSTANT:out=i.immediate;break;case DOLIR_OP_STATE_READ:out=i.aux==DOLIR_STATE_LR?0x44444444:input;break;case DOLIR_OP_AND:out=a&c;break;case DOLIR_OP_ADD:out=a+c;break;case DOLIR_OP_SUB:out=a-c;break;case DOLIR_OP_MUL:out=a*c;break;case DOLIR_OP_LSHR:out=a>>c;break;case DOLIR_OP_ASHR:out=(a>>c)|((a&0x80000000u)&&c?(~0u<<(32-c)):0);break;case DOLIR_OP_SDIV:{int32_t s;std::memcpy(&s,&a,4);out=u32(s/int32_t(c));break;}default:throw std::runtime_error("independent evaluator unsupported op");}v[i.result]=out;}return v;}
static unsigned pass=0,fail=0;static void run(const char*n,std::function<void()>f){try{f();++pass;std::cout<<"{\"test\":\""<<n<<"\",\"pass\":true}\n";}catch(const std::exception&e){++fail;std::cout<<"{\"test\":\""<<n<<"\",\"pass\":false,\"reason\":\""<<e.what()<<"\"}\n";}}
int main(){Options on;on.enabled=true;
run("default-off-byte-identity",[&]{M m;local(m);auto h=sourceFingerprint(m.f());require(discover(m.f()).candidates.empty(),"default-off discovered");require(sourceFingerprint(m.f())==h,"default-off mutated");});
run("typed-local-automatic-universal-proof",[&]{M m;local(m);auto c=find(discover(m.f(),on),5,m.root);require(verify(m.f(),c).status=="UNSAT","proof replay failed");require(c.proof.query.find("bvsrem")!=std::string::npos&&!c.proof.solver_library_sha256.empty()&&!c.proof.implementation_sha256.empty(),"proof provenance missing");});
run("signed-logical-shift-negative",[&]{M m;local(m,true);auto r=discover(m.f(),on);bool sat=false;for(auto&c:r.candidates)if(c.root==m.root&&c.expression.power==5){require(c.proof.status!="UNSAT","logical shift accepted as arithmetic");sat|=c.proof.status=="SAT";}require(sat,"semantic negative lacked concrete SAT result");});
run("local-apply-keeps-observable-intermediates",[&]{M m;local(m);auto c=find(discover(m.f(),on),5,m.root);auto cuts=sourceCutFingerprint(m.f());std::mt19937 rng(0x9289061);std::vector<u32>xs={0,1,31,32,33,0x80000000,0x80000001,0x7fffffff,0xffffffff};for(unsigned i=0;i<512;++i)xs.push_back(rng());std::vector<std::map<u32,u32>> before;for(auto x:xs)before.push_back(evaluate(m.f(),x));auto old=m.f().blocks[0].instruction_count;auto r=apply(m.f(),c,allowed(m.f(),c),on);require(r.changed,"certified local rewrite refused");require(r.replay_proof.status=="UNSAT"&&!r.replay_proof.query_sha256.empty()&&!r.function_contract_fingerprint.empty()&&!r.certification_implementation_id.empty()&&r.certification_implementation_id!="unversioned-experimental-build","fresh admission proof identity not retained");require(sourceCutFingerprint(m.f())==cuts&&m.f().blocks[0].instruction_count>=old,"source cuts changed or original DAG deleted");require(dolir_verify(&m.m,stderr),"edited DolIR invalid");for(unsigned i=0;i<xs.size();++i){auto after=evaluate(m.f(),xs[i]);for(auto [v,x]:before[i])require(after.at(v)==x,"existing observable SSA value changed");int32_t sx;std::memcpy(&sx,&xs[i],4);require(after.at(m.root)==u32(sx%32),"independent signed remainder mismatch");}});
run("forged-closed-label-no-checker",[&]{M m;local(m);auto c=find(discover(m.f(),on),5,m.root);auto a=allowed(m.f(),c);a.function.verify_evidence={};auto h=sourceFingerprint(m.f());require(!apply(m.f(),c,a,on).changed&&sourceFingerprint(m.f())==h,"unverified closure rewrote");});
run("stale-cost-and-source-proof-rejected",[&]{M m;local(m);auto c=find(discover(m.f(),on),5,m.root);auto a=allowed(m.f(),c);m.f().blocks[0].cycle_cost++;require(verify(m.f(),c).status!="UNSAT"&&!apply(m.f(),c,a,on).changed,"stale source cost proof accepted");});
run("zero-timeout-bounded-refusal",[&]{M m;local(m);auto bad=on;bad.solver_timeout_ms=0;require(discover(m.f(),bad).candidates.empty(),"zero timeout became unlimited");});
run("actual-builder-cross-word-discovery",[&]{M m;realBuilder(m);auto h=sourceFingerprint(m.f());auto c=find(discover(m.f(),on),3);require(c.conditional_on_state_forwarding&&c.source_blocks.size()>1&&!c.reaching_state_forwardings.empty(),"cross-word assumptions absent");require(verify(m.f(),c).status=="UNSAT"&&sourceFingerprint(m.f())==h,"cross-word replay or source identity failed");require(!apply(m.f(),c,allowed(m.f(),c),on).changed,"unimplemented cross-cut edit admitted");});
run("forged-cross-cut-metadata-rejected",[&]{M m;realBuilder(m);auto c=find(discover(m.f(),on),3);c.source_blocks={c.block};c.conditional_on_state_forwarding=false;auto h=sourceFingerprint(m.f());require(!apply(m.f(),c,allowed(m.f(),c),on).changed&&sourceFingerprint(m.f())==h,"forged projection metadata bypassed eligibility");});
run("effect-crossing-state-forwarding-rejected",[&]{M m;realBuilder(m,true);auto r=discover(m.f(),on);for(auto&c:r.candidates)require(!(c.expression.power==3&&c.proof.status=="UNSAT"),"projection forwarded across unknown memory callback");});
#ifdef REVIEW_WRAP_VERIFIER
run("post-rewrite-verifier-refusal-is-atomic",[&]{M m;local(m);auto c=find(discover(m.f(),on),5,m.root);auto h=sourceFingerprint(m.f());auto*ins=m.f().blocks[0].instructions;auto*types=m.f().value_types;auto ni=m.f().blocks[0].instruction_count,nv=m.f().value_count;refuse_next_verification=true;auto r=apply(m.f(),c,allowed(m.f(),c),on);require(!refuse_next_verification,"apply omitted mandatory precommit verifier");require(!r.changed&&sourceFingerprint(m.f())==h&&m.f().blocks[0].instructions==ins&&m.f().value_types==types&&m.f().blocks[0].instruction_count==ni&&m.f().value_count==nv,"validator refusal modified original IR");require(dolir_verify(&m.m,stderr),"original IR invalid after refusal");});
#endif
std::cout<<"{\"summary\":true,\"passed\":"<<pass<<",\"failed\":"<<fail<<"}\n";return fail?1:0;}
