// SPDX-License-Identifier: GPL-3.0-or-later
// Independent synthetic acceptance tests. No original/private binary data.
#include "function_certification.h"
#include "ir/dolir_builder.h"
#include <iostream>
#include <functional>
#include <vector>
#include <stdexcept>
#include <random>
using namespace dolcert;
struct Fixture { DolIRModule m{}; Fixture(std::initializer_list<u32> words){dolir_module_init(&m);std::vector<PPCInst> ins;for(u32 w:words)ins.push_back(ppc_decode(w,0x1000u+4*ins.size()));if(!dolir_build_chunk(&m,ins.data(),ins.size(),0x1000)||!dolir_verify(&m,stderr))throw std::runtime_error("fixture importer failed");}~Fixture(){dolir_module_free(&m);}DolIRFunction& f(){return m.functions[0];}};
static Contract environment(const DolIRFunction&f,EvidenceGrade grade=EvidenceGrade::Verified){Contract c;c.source_fingerprint=sourceFingerprint(f);c.entries_and_code={grade,"independent-synthetic-model:complete-entries-code-v1"};c.exception_resume={grade,"independent-synthetic-model:no-hidden-resume-v1"};c.observations={grade,"independent-synthetic-model:retain-all-cuts-no-mutation-v1"};auto fp=c.source_fingerprint;c.verify_evidence=[fp](const EvidenceRequest&r){if(r.source_fingerprint!=fp||r.address||r.value||r.model!="exact-original-cuts/full-state-observation")return false;return (r.obligation=="ENTRY_POPULATION_OR_CODE_STABILITY_UNPROVED"&&r.proof_id=="independent-synthetic-model:complete-entries-code-v1")||(r.obligation=="EXCEPTION_RESUME_CLOSURE_UNPROVED"&&r.proof_id=="independent-synthetic-model:no-hidden-resume-v1")||(r.obligation=="EXACT_OBSERVATION_AND_MUTATION_CONTRACT_UNPROVED"&&r.proof_id=="independent-synthetic-model:retain-all-cuts-no-mutation-v1");};return c;}
static void require(bool b,const char*m){if(!b)throw std::runtime_error(m);}
static bool all(const StateMask&m){for(u32 s=0;s<DOLIR_STATE_COUNT;++s)if(!dolir_state_mask_test(m.data(),(DolIRStateSlot)s))return false;return true;}
static bool hasIncoming(const Certificate&c){for(auto&b:c.blocks)if(b.returns_incoming_lr)return true;return false;}
static unsigned passed=0,failed=0;
static void run(const char*name,std::function<void()> f){try{f();++passed;std::cout<<"{\"test\":\""<<name<<"\",\"pass\":true}\n";}catch(const std::exception&e){++failed;std::cout<<"{\"test\":\""<<name<<"\",\"pass\":false,\"reason\":\""<<e.what()<<"\"}\n";}}
int main(){
 run("untrusted-leaf-open",[]{Fixture f{0x38600001,0x4e800020};auto before=sourceFingerprint(f.f());auto c=certify(f.f());require(c.status==Status::Open&&!c.abi.eligible,"no evidence must not close");require(sourceFingerprint(f.f())==before&&!c.mutates_ir&&!c.prunes_code&&!c.changes_timing,"analysis mutated source");});
 run("trusted-synthetic-leaf-closed",[]{Fixture f{0x38600001,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Closed&&c.analysis_complete,"synthetic leaf not closed under explicit verified model");require(hasIncoming(c),"incoming LR return provenance missing");require(!c.abi.guest_stack_elision_allowed,"stack elision accidentally granted");});
 run("conditional-model-stays-conditional",[]{Fixture f{0x38600001,0x4e800020};auto c=certify(f.f(),environment(f.f(),EvidenceGrade::Conditional));require(c.status==Status::Conditional&&!c.abi.eligible,"conditional assumptions promoted");});
 run("verified-label-without-checker",[]{Fixture f{0x38600001,0x4e800020};auto e=environment(f.f());e.verify_evidence={};auto c=certify(f.f(),e);require(c.status!=Status::Closed&&!c.abi.eligible,"verified label alone closed");});
 run("rejecting-evidence-checker",[]{Fixture f{0x38600001,0x4e800020};auto e=environment(f.f());e.verify_evidence=[](const EvidenceRequest&){return false;};auto c=certify(f.f(),e);require(c.status!=Status::Closed&&!c.abi.eligible,"rejected evidence closed");});
 run("fingerprint-stale-rejected",[]{Fixture f{0x38600001,0x4e800020};auto c=environment(f.f());f.f().blocks[0].cycle_cost++;auto r=certify(f.f(),c);require(r.status==Status::Open&&!r.abi.eligible,"stale fingerprint accepted");});
 run("direct-call-opaque",[]{Fixture f{0x48000101,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!c.abi.eligible,"unproved callee closed");require(all(c.effect_summary.state_may_write),"opaque call under-approximates writes");require(!hasIncoming(c),"call return mistaken for incoming LR");});
 run("conditional-call-both-arms",[]{Fixture f{0x41820101,0x38600001,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open,"unproved conditional call closed");unsigned n=0;for(auto&e:c.edges)n+=e.block==0;require(n>=2,"conditional transfer lost an arm");});
 run("direct-tail-unresolved",[]{Fixture f{0x48000100};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!c.abi.eligible,"external tail behavior inferred");});
 run("conditional-tail-both-arms",[]{Fixture f{0x41820100,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open,"external conditional tail closed");unsigned n=0;for(auto&e:c.edges)n+=e.block==0;require(n>=2,"conditional tail lost fallthrough");});
 run("ctr-unknown-not-return",[]{Fixture f{0x7c6903a6,0x4e800420};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!hasIncoming(c),"unknown CTR inferred as return");});
 run("constant-ctr-local-target",[]{Fixture f{0x3860100c,0x7c6903a6,0x4e800420,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.cfg==Status::Closed,"constant local CTR target not proved");});
 run("register-lr-roundtrip",[]{Fixture f{0x7ca802a6,0x38600001,0x7ca803a6,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Closed&&hasIncoming(c),"register LR roundtrip lost provenance");});
 run("register-lr-corruption",[]{Fixture f{0x7ca802a6,0x38a00000,0x7ca803a6,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(!hasIncoming(c)&&c.status==Status::Open,"corrupted LR copy trusted");});
 run("saved-lr-memory-not-trusted",[]{Fixture f{0x7c0802a6,0x90010004,0x80010004,0x7c0803a6,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!hasIncoming(c),"stack convention treated as immutable save");require(c.effect_summary.memory_read&&c.effect_summary.memory_write&&c.effect_summary.fault,"stack access effects absent");});
 run("saved-lr-alias-corruption",[]{Fixture f{0x7c0802a6,0x90010004,0x90610004,0x80010004,0x7c0803a6,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!hasIncoming(c),"overwritten LR save trusted");});
 run("conditional-lr-return",[]{Fixture f{0x4d820020,0x38600000,0x4e800020};auto c=certify(f.f(),environment(f.f()));unsigned n=0;for(auto&e:c.edges)n+=e.block==0;require(n>=2,"conditional LR return loses fallthrough");require(hasIncoming(c),"conditional LR provenance missing");});
 run("memory-fault-update-form",[]{Fixture f{0x84640004,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&c.effect_summary.fault&&c.effect_summary.memory_read,"update load incorrectly nofault");require(all(c.effect_summary.state_may_write),"uncontracted service may mutate state");});
 run("memory-cached-alias",[]{Fixture f{0x3c808000,0x80640000,0x3ca0c000,0x90650000,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&c.effect_summary.memory_read&&c.effect_summary.memory_write,"address domains treated as disjoint proof");});
 run("mutable-table-target",[]{Fixture f{0x80640000,0x7c6903a6,0x4e800420};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&!hasIncoming(c),"mutable table target closed");});
 run("opaque-system-effect",[]{Fixture f{0x44000002,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&all(c.effect_summary.state_may_write),"opaque service underapproximated");});
 run("loop-conservative-fixedpoint",[]{Fixture f{0x38630001,0x2c03000a,0x4180fff8,0x4e800020};auto c=certify(f.f(),environment(f.f()));require(c.analysis_complete,"simple loop did not converge");require(!c.abi.termination_proved,"termination inferred from CFG");});
 run("interior-entry-does-not-inherit",[]{Fixture f{0x7ca802a6,0x38600001,0x7ca803a6,0x4e800020};auto e=environment(f.f());e.entry_blocks={0,2};auto c=certify(f.f(),e);require(c.status==Status::Open&&!hasIncoming(c),"interior entry inherits LR copy");});
 run("zero-analysis-budget-fails-closed",[]{Fixture f{0x38600001,0x4e800020};auto e=environment(f.f());e.max_iterations=0;auto c=certify(f.f(),e);require(c.status==Status::Open&&!c.analysis_complete,"analysis budget exhaustion accepted");});
 run("opaque-tail-output-mask-consistency",[]{Fixture f{0x41820100,0x4e800020};auto c=certify(f.f(),environment(f.f()));for(unsigned n=0;n<DOLIR_STATE_MASK_WORDS;++n)require((c.abi.may_live_out[n]&c.effect_summary.state_may_write[n])==c.effect_summary.state_may_write[n],"ABI may outputs narrower than final effects");require(c.returns==Status::Open,"unknown external tail counted as return closure");});
 run("immutable-plain-load-positive",[]{Fixture f{0x80602000,0x4e800020};auto e=environment(f.f());auto ordinary=e.verify_evidence;e.immutable_words.push_back({0x2000,0x12345678,{EvidenceGrade::Verified,"synthetic-immutable-memory-v1"},{EvidenceGrade::Verified,"synthetic-plain-read-v1"}});auto fp=e.source_fingerprint;e.verify_evidence=[ordinary,fp](const EvidenceRequest&r){return ordinary(r)||(r.source_fingerprint==fp&&r.address==0x2000&&r.value==0x12345678&&((r.obligation=="IMMUTABLE_LIFETIME_UNPROVED"&&r.proof_id=="synthetic-immutable-memory-v1")||(r.obligation=="PLAIN_READ_UNPROVED"&&r.proof_id=="synthetic-plain-read-v1")));};auto c=certify(f.f(),e);require(c.status==Status::Closed&&c.effect_summary.memory_read&&!c.effect_summary.fault,"independently checked immutable plain load did not close");});
 run("immutable-label-unverified-rejected",[]{Fixture f{0x80602000,0x4e800020};auto e=environment(f.f());e.immutable_words.push_back({0x2000,0x12345678,{EvidenceGrade::Verified,"unregistered-proof"},{EvidenceGrade::Verified,"unregistered-proof"}});auto c=certify(f.f(),e);require(c.status==Status::Open&&c.effect_summary.fault,"unregistered immutable memory evidence trusted");});
 run("malformed-negative-op-rejected",[]{Fixture f{0x38600001,0x4e800020};f.f().blocks[0].instructions[0].op=static_cast<DolIROp>(-1);auto c=certify(f.f());require(!c.valid_ir&&c.status==Status::Open,"negative opcode accepted");});
 run("malformed-null-instructions-rejected",[]{Fixture f{0x38600001,0x4e800020};auto*p=f.f().blocks[0].instructions;f.f().blocks[0].instructions=nullptr;auto c=certify(f.f());f.f().blocks[0].instructions=p;require(!c.valid_ir&&c.status==Status::Open,"null instruction array accepted");});
 run("invalid-entry-set-rejected",[]{Fixture f{0x38600001,0x4e800020};auto e=environment(f.f());e.entry_blocks={4};auto c=certify(f.f(),e);require(c.status==Status::Open&&!c.abi.eligible,"invalid entry accepted");});
 run("constant-target-property-256-programs",[]{std::mt19937 rng(0x19289061);for(unsigned trial=0;trial<256;++trial){std::vector<PPCInst> in;auto emit=[&](u32 w){in.push_back(ppc_decode(w,0x1000+4*in.size()));};u32 value=static_cast<int16_t>(rng());emit(0x38600000|(value&65535));for(unsigned n=0;n<12;++n){u32 k=rng()&65535;switch(rng()%6){case 0:emit(0x38630000|k);value+=static_cast<int16_t>(k);break;case 1:emit(0x3c630000|k);value+=k<<16;break;case 2:emit(0x60630000|k);value|=k;break;case 3:emit(0x68630000|k);value^=k;break;case 4:emit(0x70630000|k);value&=k;break;default:emit(0x1c630000|k);value*=static_cast<int16_t>(k);break;}}emit(0x7c6903a6);emit(0x4e800420);DolIRModule m;dolir_module_init(&m);require(dolir_build_chunk(&m,in.data(),in.size(),0x1000)&&dolir_verify(&m,stderr),"property source importer failed");auto c=certify(m.functions[0],environment(m.functions[0]));bool found=false;for(auto&e:c.edges)if(e.block==in.size()-1&&e.target_provenance=="proved-value-constant"){found=true;if(e.target_address!=(value&~3u)){dolir_module_free(&m);throw std::runtime_error("constant transfer disagrees with independent modular arithmetic");}}dolir_module_free(&m);if(!found){u32 target=value&~3u;require(target>=0x1000&&target<0x1000+4*in.size()&&c.status==Status::Open,"acyclic constant target unresolved or cyclic uncertainty erased");}}});
 run("target-index-address-mismatch-rejected",[]{Fixture f{0x38600001,0x4e800020};f.f().blocks[0].terminator.target_addresses[0]+=4;auto c=certify(f.f());require(!c.valid_ir&&c.status==Status::Open,"inconsistent target index/address accepted");});
 run("entry-population-bound-to-checker",[]{Fixture f{0x38600001,0x4e800020};auto e=environment(f.f());auto ordinary=e.verify_evidence;e.verify_evidence=[ordinary](const EvidenceRequest&r){return r.entry_blocks==std::vector<u32>{0}&&ordinary(r);};e.entry_blocks={0,1};auto c=certify(f.f(),e);require(c.status!=Status::Closed&&!c.abi.eligible,"complete-entry evidence reused for changed entry set");});
 run("unknown-target-budget-never-empty-closed",[]{Fixture f{0x7c6903a6,0x4e800420};auto e=environment(f.f());e.max_edges=0;auto c=certify(f.f(),e);require(c.status==Status::Open&&!c.analysis_complete&&!c.abi.eligible,"indirect target budget exhausted into empty closed set");});
 run("region-boundary-not-function-end",[]{Fixture f{0x38600001};auto c=certify(f.f(),environment(f.f()));require(c.status==Status::Open&&c.cfg==Status::Open&&c.returns==Status::Open,"source window end treated as function return");});
 std::cout<<"{\"summary\":true,\"passed\":"<<passed<<",\"failed\":"<<failed<<"}\n";return failed?1:0;
}
