# Experimental host-only analysis. Nothing here is linked into dr_app/dr_cpu.
find_package(OpenSSL REQUIRED COMPONENTS Crypto)

# Conservative semantic closure: watch contents and additions/removals, including
# the recipes that define compilation and identity. Labels never contain paths
# outside the source tree. Proofs separately identify the actual loaded solver.
file(GLOB_RECURSE _pipeline_sources CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h")
file(GLOB _pipeline_drivers CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/tools/function_pipeline/*.cpp")
list(APPEND _pipeline_sources ${_pipeline_drivers})
list(APPEND _pipeline_sources
    "${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.txt"
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/function_pipeline.cmake")
list(SORT _pipeline_sources)
# Bind selected compiler/crypto files without leaking installation paths. This
# is a build identity, not a hermetic attestation of the host or dynamic loader.
set(_pipeline_dependency_digest "")
set(_pipeline_dependency_files "${CMAKE_C_COMPILER}" "${CMAKE_CXX_COMPILER}")
get_target_property(_crypto_configurations OpenSSL::Crypto IMPORTED_CONFIGURATIONS)
foreach(_configuration IN ITEMS "" NOCONFIG RELEASE DEBUG RELWITHDEBINFO MINSIZEREL ${_crypto_configurations})
    if(_configuration)
        set(_location_property "IMPORTED_LOCATION_${_configuration}")
    else()
        set(_location_property "IMPORTED_LOCATION")
    endif()
    get_target_property(_crypto_location OpenSSL::Crypto "${_location_property}")
    if(_crypto_location AND EXISTS "${_crypto_location}")
        list(APPEND _pipeline_dependency_files "${_crypto_location}")
    endif()
endforeach()
list(REMOVE_DUPLICATES _pipeline_dependency_files)
foreach(_dependency IN LISTS _pipeline_dependency_files)
    if(EXISTS "${_dependency}")
        file(SHA256 "${_dependency}" _dependency_hash)
        string(APPEND _pipeline_dependency_digest "${_dependency_hash};")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_dependency}")
    endif()
endforeach()
set(_crypto_headers "")
foreach(_include IN ITEMS "${OPENSSL_INCLUDE_DIR}" ${CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES} ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
    file(GLOB _headers CONFIGURE_DEPENDS "${_include}/openssl/*.h")
    list(APPEND _crypto_headers ${_headers})
endforeach()
list(REMOVE_DUPLICATES _crypto_headers)
list(SORT _crypto_headers)
foreach(_header IN LISTS _crypto_headers)
    file(SHA256 "${_header}" _dependency_hash)
    get_filename_component(_header_label "${_header}" NAME)
    string(APPEND _pipeline_dependency_digest "${_header_label};${_dependency_hash};")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_header}")
endforeach()
string(SHA256 _pipeline_dependency_hash "${_pipeline_dependency_digest}")
set(_pipeline_digest "")
set(_pipeline_rows "")
foreach(_file IN LISTS _pipeline_sources)
    file(SHA256 "${_file}" _hash)
    file(RELATIVE_PATH _label "${CMAKE_CURRENT_SOURCE_DIR}" "${_file}")
    string(APPEND _pipeline_digest "${_label};${_hash};")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")
    if(NOT _pipeline_rows STREQUAL "")
        string(APPEND _pipeline_rows ",\n")
    endif()
    string(APPEND _pipeline_rows "    {\"path\":\"${_label}\",\"sha256\":\"${_hash}\"}")
endforeach()
if(CMAKE_CONFIGURATION_TYPES)
    set(_pipeline_configurations ${CMAKE_CONFIGURATION_TYPES})
else()
    set(_pipeline_configurations "${CMAKE_BUILD_TYPE}")
    if(NOT _pipeline_configurations)
        set(_pipeline_configurations "default")
    endif()
endif()
set(_certification_definitions "")
set(_idiom_definitions "")
foreach(_configuration IN LISTS _pipeline_configurations)
    string(TOUPPER "${_configuration}" _configuration_upper)
    string(SHA256 _pipeline_flags "${_configuration};${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_C_FLAGS_${_configuration_upper}};${CMAKE_CXX_FLAGS_${_configuration_upper}};${CMAKE_EXE_LINKER_FLAGS};${CMAKE_EXE_LINKER_FLAGS_${_configuration_upper}};${CMAKE_INTERPROCEDURAL_OPTIMIZATION};${CMAKE_INTERPROCEDURAL_OPTIMIZATION_${_configuration_upper}};${CMAKE_C_COMPILER_TARGET};${CMAKE_CXX_COMPILER_TARGET};${CMAKE_SYSROOT};${CMAKE_OSX_ARCHITECTURES};${CMAKE_MSVC_RUNTIME_LIBRARY};${CMAKE_POSITION_INDEPENDENT_CODE};${CMAKE_C_EXTENSIONS};${CMAKE_CXX_EXTENSIONS};${CMAKE_C_STANDARD};${CMAKE_CXX_STANDARD};${CMAKE_C_STANDARD_REQUIRED};${CMAKE_CXX_STANDARD_REQUIRED};${CMAKE_C_BYTE_ORDER};${CMAKE_CXX_BYTE_ORDER};${CMAKE_BUILD_RPATH};${CMAKE_INSTALL_RPATH};${CMAKE_SYSROOT_COMPILE};${CMAKE_SYSROOT_LINK};${CMAKE_OSX_DEPLOYMENT_TARGET};${CMAKE_C_VISIBILITY_PRESET};${CMAKE_CXX_VISIBILITY_PRESET};${CMAKE_VISIBILITY_INLINES_HIDDEN};${CMAKE_C_COMPILER_FRONTEND_VARIANT};${CMAKE_CXX_COMPILER_FRONTEND_VARIANT};${CMAKE_C_SIMULATE_ID};${CMAKE_C_SIMULATE_VERSION};${CMAKE_CXX_SIMULATE_ID};${CMAKE_CXX_SIMULATE_VERSION};${CMAKE_STATIC_LINKER_FLAGS};${CMAKE_STATIC_LINKER_FLAGS_${_configuration_upper}}")
    set(_pipeline_recipe "integrated-function-pipeline-v1;${CMAKE_C_COMPILER_ID};${CMAKE_C_COMPILER_VERSION};${CMAKE_CXX_COMPILER_ID};${CMAKE_CXX_COMPILER_VERSION};${CMAKE_SYSTEM_NAME};${CMAKE_SYSTEM_PROCESSOR};${CMAKE_SIZEOF_VOID_P};${CMAKE_GENERATOR_PLATFORM};${CMAKE_GENERATOR_TOOLSET};${CMAKE_C_COMPILER_ARCHITECTURE_ID};${CMAKE_CXX_COMPILER_ARCHITECTURE_ID};${OPENSSL_VERSION};${DOLRECOMP_ENABLE_LLVM};${LLVM_PACKAGE_VERSION};${_pipeline_flags};${_pipeline_dependency_hash};${_pipeline_digest}")
    string(SHA256 DOLRECOMP_CERTIFICATION_ID "certification;${_pipeline_recipe}")
    string(SHA256 DOLRECOMP_IDIOM_ID "verified-idioms;${_pipeline_recipe}")
    if(CMAKE_CONFIGURATION_TYPES)
        list(APPEND _certification_definitions "$<$<CONFIG:${_configuration}>:DOLCERT_IMPLEMENTATION_ID=\"${DOLRECOMP_CERTIFICATION_ID}\">")
        list(APPEND _idiom_definitions "$<$<CONFIG:${_configuration}>:DOLIDIOM_IMPLEMENTATION_SHA256=\"${DOLRECOMP_IDIOM_ID}\">")
        set(_identity_filename "function-pipeline-identity-${_configuration}.json")
    else()
        list(APPEND _certification_definitions DOLCERT_IMPLEMENTATION_ID="${DOLRECOMP_CERTIFICATION_ID}")
        list(APPEND _idiom_definitions DOLIDIOM_IMPLEMENTATION_SHA256="${DOLRECOMP_IDIOM_ID}")
        set(_identity_filename "function-pipeline-identity.json")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${_identity_filename}"
        "{\n  \"schema\":\"dolrecomp.integrated-function-pipeline-build.v1\",\n  \"configuration\":\"${_configuration}\",\n  \"certification_id\":\"${DOLRECOMP_CERTIFICATION_ID}\",\n  \"idiom_id\":\"${DOLRECOMP_IDIOM_ID}\",\n  \"flags_sha256\":\"${_pipeline_flags}\",\n  \"selected_dependencies_sha256\":\"${_pipeline_dependency_hash}\",\n  \"inputs\":[\n${_pipeline_rows}\n  ]\n}\n")
endforeach()

if(CMAKE_CONFIGURATION_TYPES)
    set(_pipeline_identity_path "${CMAKE_CURRENT_BINARY_DIR}/function-pipeline-identity-$<CONFIG>.json")
    set(_idiom_evidence_path "${CMAKE_CURRENT_BINARY_DIR}/idiom-evidence/$<CONFIG>")
else()
    set(_pipeline_identity_path "${CMAKE_CURRENT_BINARY_DIR}/function-pipeline-identity.json")
    set(_idiom_evidence_path "${CMAKE_CURRENT_BINARY_DIR}/idiom-evidence")
endif()

add_library(dr_function_certification STATIC
    src/analysis/function_certification/function_certification.cpp
    src/analysis/function_certification/fingerprint.cpp
    src/analysis/function_certification/json.cpp)
target_include_directories(dr_function_certification PUBLIC
    ${DOLRECOMP_SRC}/analysis/function_certification)
target_compile_definitions(dr_function_certification PRIVATE
    ${_certification_definitions})
target_link_libraries(dr_function_certification PUBLIC dr_ir PRIVATE dr_native_analysis OpenSSL::Crypto)
add_executable(certify_words tools/function_pipeline/certify_words.cpp)
target_link_libraries(certify_words PRIVATE dr_function_certification)
add_executable(test_function_certification tests/function_pipeline/test_certification.cpp)
target_link_libraries(test_function_certification PRIVATE dr_function_certification)
add_test(NAME function_certification COMMAND test_function_certification)
add_executable(test_independent_certification tests/function_pipeline/test_independent_certification.cpp)
target_link_libraries(test_independent_certification PRIVATE dr_function_certification)
add_test(NAME independent_function_certification COMMAND test_independent_certification)
find_package(Python3 COMPONENTS Interpreter QUIET)
if(Python3_Interpreter_FOUND)
    add_test(NAME function_certification_schema COMMAND ${Python3_EXECUTABLE}
        ${CMAKE_CURRENT_SOURCE_DIR}/tests/function_pipeline/test_report_schema.py $<TARGET_FILE:certify_words>)
endif()

if(DOLRECOMP_ENABLE_VERIFIED_IDIOMS)
    add_library(dr_verified_idioms STATIC src/analysis/verified_idioms/verified_idioms.cpp)
    target_include_directories(dr_verified_idioms PUBLIC ${DOLRECOMP_SRC}/analysis/verified_idioms)
    target_compile_definitions(dr_verified_idioms PRIVATE ${_idiom_definitions})
    target_link_libraries(dr_verified_idioms PUBLIC dr_function_certification PRIVATE ${CMAKE_DL_LIBS} OpenSSL::Crypto)
    add_executable(discover_words tools/function_pipeline/discover_words.cpp)
    target_link_libraries(discover_words PRIVATE dr_verified_idioms)
    add_executable(test_verified_idioms tests/function_pipeline/test_verified_idioms.cpp)
    target_link_libraries(test_verified_idioms PRIVATE dr_verified_idioms)
    add_test(NAME verified_idioms COMMAND test_verified_idioms ${_idiom_evidence_path})
    add_executable(test_idiom_apply_atomic tests/function_pipeline/test_apply_atomic.cpp)
    target_link_libraries(test_idiom_apply_atomic PRIVATE dr_verified_idioms)
    target_link_options(test_idiom_apply_atomic PRIVATE "-Wl,--wrap=dolir_verify")
    add_test(NAME verified_idioms_failure_atomic COMMAND test_idiom_apply_atomic)
    add_executable(test_independent_idioms tests/function_pipeline/test_independent_idioms.cpp)
    target_compile_definitions(test_independent_idioms PRIVATE REVIEW_WRAP_VERIFIER=1)
    target_link_libraries(test_independent_idioms PRIVATE dr_verified_idioms)
    target_link_options(test_independent_idioms PRIVATE "-Wl,--wrap=dolir_verify")
    add_test(NAME independent_verified_idioms COMMAND test_independent_idioms)
    add_executable(test_pipeline_provenance_failures tests/function_pipeline/test_provenance_failures.cpp)
    target_link_libraries(test_pipeline_provenance_failures PRIVATE dr_verified_idioms OpenSSL::Crypto)
    target_link_options(test_pipeline_provenance_failures PRIVATE "-Wl,--wrap=dlsym")
    add_test(NAME function_pipeline_provenance_failures COMMAND test_pipeline_provenance_failures)
    set_tests_properties(function_pipeline_provenance_failures PROPERTIES TIMEOUT 300)
    if(Python3_Interpreter_FOUND)
        add_test(NAME function_pipeline_cli_failures COMMAND ${Python3_EXECUTABLE}
            ${CMAKE_CURRENT_SOURCE_DIR}/tests/function_pipeline/test_cli_failures.py
            $<TARGET_FILE:certify_words> $<TARGET_FILE:discover_words>)
        add_test(NAME verified_idioms_proof_replay COMMAND ${Python3_EXECUTABLE}
            ${CMAKE_CURRENT_SOURCE_DIR}/tests/function_pipeline/replay.py
            ${_idiom_evidence_path}/all-proofs --expected-count 468
            --identity-manifest ${_pipeline_identity_path})
        set_tests_properties(verified_idioms PROPERTIES FIXTURES_SETUP idiom_proofs)
        set_tests_properties(verified_idioms_proof_replay PROPERTIES FIXTURES_REQUIRED idiom_proofs)
        find_program(DOLRECOMP_ANALYSIS_CLANG NAMES clang)
        if(DOLRECOMP_ANALYSIS_CLANG)
            add_test(NAME verified_idioms_expression_differential COMMAND ${CMAKE_COMMAND} -E env
                "CLANG=${DOLRECOMP_ANALYSIS_CLANG}" ${Python3_EXECUTABLE}
                ${CMAKE_CURRENT_SOURCE_DIR}/tests/function_pipeline/differential.py
                ${_idiom_evidence_path})
            set_tests_properties(verified_idioms_expression_differential PROPERTIES FIXTURES_REQUIRED idiom_proofs)
        endif()
    endif()
endif()
